
package wst.lab1.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MenagerieService", targetNamespace = "http://ws.lab1.wst/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MenagerieService {


    /**
     * @param arrival
     * @param name
     * @param animal
     * @param health
     * @param id
     * @param breed
     * @return returns java.util.List<wst.lab1.ws.Menagerie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filter", targetNamespace = "http://ws.lab1.wst/", className = "wst.lab1.ws.Filter")
    @ResponseWrapper(localName = "filterResponse", targetNamespace = "http://ws.lab1.wst/", className = "wst.lab1.ws.FilterResponse")
    @Action(input = "http://ws.lab1.wst/MenagerieService/filterRequest", output = "http://ws.lab1.wst/MenagerieService/filterResponse")
    public List<Menagerie> filter(
            @WebParam(name = "id", targetNamespace = "")
                    Long id,
            @WebParam(name = "animal", targetNamespace = "")
                    String animal,
            @WebParam(name = "name", targetNamespace = "")
                    String name,
            @WebParam(name = "breed", targetNamespace = "")
                    String breed,
            @WebParam(name = "health", targetNamespace = "")
                    String health,
            @WebParam(name = "arrival", targetNamespace = "")
                    XMLGregorianCalendar arrival);

    /**
     * @return returns java.util.List<wst.lab1.ws.Menagerie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws.lab1.wst/", className = "wst.lab1.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws.lab1.wst/", className = "wst.lab1.ws.FindAllResponse")
    @Action(input = "http://ws.lab1.wst/MenagerieService/findAllRequest", output = "http://ws.lab1.wst/MenagerieService/findAllResponse")
    public List<Menagerie> findAll();

}
